spring.application.name=gestionestacionamiento

#Configuraciones generales de la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/estacionamiento
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Configuraciones JWT
jwt.secret=c2VjdXJpdHktc2VjcmV0LWtleS1wYXJhLWdlc3Rpb24tZGVzdGFjaW9uYW1pZW50by0yMDI2LXZlcnktbC1hcmdvLXNlY3Vyby1wYXJhLWp3dC1yZW1lbWJlci1jbGF2ZS1zZWdt
jwt.expiration=86400000

